Inside try block 1
Hello, exception
Inside try block 2
123
